name: 🐛 Bug report
description: Create a report & Describe a problem to help us improve
labels: your_label
assignees: your_username

---

body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       Some general tips:

  #       - Is this really a problem?
  #       - Is this a problem here?
  #       - Can this be solved in a different way?

  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        - label: I read the [support docs](https://github.com/pi-apps/.github/blob/main/support.md)
          required: true
        - label: I read the [contributing guide](https://github.com/pi-apps/.github/blob/main/contributing.md)
          required: true
        - label: I agree to follow the [code of conduct](https://github.com/pi-apps/.github/blob/main/code-of-conduct.md)
          required: true
        - label: I searched [issues](https://github.com/search?q=user%3Api-apps&type=Issues) and couldn’t find anything (or linked relevant results below)
          required: true

  - type: input
    id: affected-versions
    attributes:
      label: Affected packages and versions
      description: Please test using the latest version of the relevant packages to make sure your issue has not already been fixed.
    validations:
      required: true

  - type: input
    id: runnable-example
    attributes:
      label: Link to runnable example
      description: |
        Link to repository or sandbox with runnable example of the issue.
        Alternatively, use the next section *Steps to reproduce*.

        # Some CodeSandbox starters:
        # - [](https://codesandbox.io/s/)
        # - [](https://codesandbox.io/s/)
        # - [](https://codesandbox.io/s/)
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        How did this happen? Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

        **To Reproduce**
        Steps to reproduce the behavior:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen? A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

- type: upload
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add Links to screenshots to help explain your problem.
    validations:
      required: false

  - type: dropdown
    id: javascript-runtime
    attributes:
      label: Runtime
      description: |
        What JavaScript runtime are you using to build or run the code?
        **Note**: for ECMASCript modules (ESM) in Node, at minimum Node.js 12.20, 14.14, or 16.0 is required.
      multiple: true
      options:
        - Node v16
        - Node v14
        - Node v12
        - Deno v1
        - Electron v13
        - Electron v12
        - Electron v11
        - Other (please specify in steps to reproduce)
    validations:
      required: false

  - type: dropdown
    id: package-manager
    attributes:
      label: Package manager
      description: What package manager are you using?
      multiple: true
      options:
        - npm v6
        - npm v7
        - yarn v1
        - yarn v2
        - pnpm
        - Other (please specify in steps to reproduce)
    validations:
      required: false

  - type: dropdown
    id: operating-system
    attributes:
      label: OS
      description: |
        What operating system are you using?
          **Desktop (please complete the following information):**
          - OS: [e.g. iOS]
          - Browser [e.g. chrome, safari]
          - Version [e.g. 22]

          **Smartphone (please complete the following information):**
          - Device: [e.g. iPhone6]
          - OS: [e.g. iOS8.1]
          - Browser [e.g. stock browser, safari]
          - Version [e.g. 22]
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Other (please specify in steps to reproduce)
    validations:
      required: false

  - type: dropdown
    id: build-tools
    attributes:
      label: Build and bundle tools
      description: What, if any, tools are used to build or bundle the project?
      multiple: true
      options:
        - Webpack
        - Rollup
        - esbuild
        - Parcel
        - Create React App
        - Gatsby
        - Next.js
        - Docusaurus
        - Snowpack
        - Vite
        - Other (please specify in additonal info)
    validations:
      required: false
