name: 🚀 Feature request
description: Suggest an idea for this project
labels: your_labels
assignees: your_username

---

body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       Some general tips:

  #       - Is this really a problem?
  #       - Is this a problem here?

  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        - label: I read the [support docs](https://github.com/pi-apps/.github/blob/main/support.md)
          required: true
        - label: I read the [contributing guide](https://github.com/pi-apps/.github/blob/main/contributing.md)
          required: true
        - label: I agree to follow the [code of conduct](https://github.com/pi-apps/.github/blob/main/code-of-conduct.md)
          required: true
        - label: I searched [issues](https://github.com/search?q=user%3Api-apps&type=Issues) and couldn’t find anything (or linked relevant results below)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What should happen? Please describe the desired behavior. A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What are the alternative solutions? Can this be solved in a different way? A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Alternatives
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
